### ISSUE TITLE
Doesn't pass the PouchDB test suite

### ISSUE THREAD

**Issue by nolanlawson** [medea/medeadown#7]
Steps to repro:

```
hub clone pouchdb/pouchdb
cd pouchdb
npm install medeadown
LEVEL_ADAPTER=medeadown npm run test-node
```

Fails on the very first test with `Uncaught AssertionError: expected {} to not exist`. My hunch is that this is due to MedeaDOWN not exporting a LevelDOWN-compatible API in the same way that most *down adapters do, but I haven't investigated yet. This issue is just a heads-up in case you're curious and want to investigate. :smiley:

For more info about how to set up your project to run the PouchDB test suite (e.g. in Travis) and how to debug, check out [this guide](https://gist.github.com/nolanlawson/f2f4d7e2e6f426502b94). *down adapters that are known to pass the test include LevelDOWN, MemDOWN, localstorage-down, level-js, riakdown, and redisdown.

**Comment by Ivshti** [comment]
Can you post the full error log? I tried to setup the test quickly but it turns out I have to set up CouchDB too, can't do that now.

**Comment by nolanlawson** [comment]
Sorry, forgot that detail! You can also run a PouchDB Server backed by medeadown instead, but often it's easier to use CouchDB for debugging.

And you're right; the fix is easy. It looks like medeadown doesn't create a new database if the file isn't found?

```
"OpenError: _pouch_testdb: No such file or directory
    at LevelUP.open (/Users/nolan/workspace/node-levelup/lib/levelup.js:118:34)
    at MedeaDOWN._open (/Users/nolan/workspace/pouchdb/node_modules/medeadown/medeadown.js:28:14)
    at open (/Users/nolan/workspace/pouchdb/node_modules/medeadown/node_modules/leveldown-open/leveldown-open.js:15:18)
    at Object.cb [as oncomplete] (fs.js:169:19)"
```

**Comment by Ivshti** [comment]
Yes. I also met this issue once, I think it's a matter of mkdir vs mkdirp, but I solved it in my app instead of in Medea. It does make sense, Medea should not be expected to auto-create the directory the data should reside in. Unless of course LevelDB does that.

**Comment by nolanlawson** [comment]
LevelDB does. :) In fact, the PouchDB test suite passes against LevelDOWN, MemDOWN, level.js, localstorage-down, riakdown, and redisdown. So you'd be joining the crowd. :D

**Comment by Ivshti** [comment]
Well from these only LevelDOWN uses the FS directly. But yes, I agree, a mkdirp should get in there.
